analyzer:
  errors:
    prefer_single_quotes: ignore
    avoid_dynamic_calls: ignore
include: package:very_good_analysis/analysis_options.6.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
