name: loop
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  app_links: ^6.4.0
  auto_route: ^9.3.0+1
  bloc: ^9.0.0
  dio: ^5.8.0+1
  equatable: ^2.0.7
  firebase_core: ^3.12.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_displaymode: ^0.6.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  flutter_screenutil: ^5.9.3
  get_it: ^8.0.3
  injectable: ^2.5.0
  injectable_generator: ^2.7.0
  intl: ^0.19.0
  slide_countdown: ^2.0.2

dev_dependencies:
  auto_route_generator: ^9.3.1
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  rename: ^3.0.2
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/json/
    - assets/rive/
    - assets/svgs/


flutter_gen:
  output: lib/gen/
  line_length: 50
  integrations:
    flutter_svg: true
    flare_flutter: true
  assets:
    enabled: true
    outputs:
      class_name: MyAssets
      package_parameter_enabled: false
      style: dot-delimiter


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo_1024.png"
  min_sdk_android: 21